### PR TITLE
Define file format

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Related to #76.

@TheNeikos , @neithernut Would like to hear suggestions.

### CODE REVIEW

**Comment by neithernut** [comment]
Having an `imag` section is a good idea, but maybe we should explicitly allow modules to store metadata in other sections, _if_ that data is of general interest to a user.

**Comment by TheNeikos** [comment]
@neithernut Sections can be nested arbitrarily deep, so a module would be free to for example do this:

```toml
[imag]
id = 'asdasdfasdf12334555'
module = 'random_names_generator'

[imag.names_generated]
proper = ["Suzy", "Allen"]
first = []
```

**Comment by matthiasbeyer** [comment]
@neithernut what @TheNeikos suggested is exactly the way I would do it. I'll describe it in the document, as it seems this should be stated...

**Comment by neithernut** [comment]
I do know that you TOML supports nesting, but it seems a bit weird if general purpose data is stored under the `imag` section. Then again, most users will probably use a tool for extracting metadata anyway...

**Comment by matthiasbeyer** [comment]
No, I think this is a good way to do it. At least, it is not _general_ purpose data, it is _module specific_ data, so it makes sense to me to store it in a section `imag.<modulename>`.

**Comment by neithernut** [comment]
Still not quite sure, but for the sake of progress I agree to use this convention, at least for now.

**Comment by TheNeikos** [comment]
We could reserve a [content] area, thus not allowing a 'content' module, making that the default content section, and allowing other modules thus to make their own section, not inside imag.

**Comment by matthiasbeyer** [comment]
@TheNeikos You mean that the content of a file goes into the `[content]` section of the `TOML`-Part?

I propose a structure like this in this PR:

```
---
[imag]
<bla>
[imag.somemodule]
<module specific bla>
---

<content>
```

So the content has its own area in this case... (`content` is user input in this case. For some modules there is no user input, of course). I'm not quite sure what you mean with your comment.

**Comment by TheNeikos** [comment]
Ah ok, in that case then, both of our arguments do not apply I think.

**Comment by matthiasbeyer** [comment]
> both of our arguments

@TheNeikos what `both` arguments? You mean the one from @neithernut on "general purpose data"?

Anyways, do you ACK this?

**Comment by TheNeikos** [comment]
Please do add an example, since there was a misunderstanding on my part, and I think with an example that would have been avoided.

**Comment by TheNeikos** [comment]
Alright, now, I think that we can drop the imag prefix for the tables, since the content will always be seperate. I see no reason for it being nested from the get go.

**Comment by matthiasbeyer** [comment]
@TheNeikos see 535c2f4

**Comment by TheNeikos** [comment]
That seems good to me!

:+1:

**Comment by matthiasbeyer** [comment]
@homu r+

**Pull request merged**
