### PR TITLE
Implement Store::retrieve_copy()

### PR DESCRIPTION
**Pull request by neithernut**
Targets #105.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@TheNeikos what about this one?

**Comment by TheNeikos** [comment]
:? It doesn't copy!

**Comment by neithernut** [comment]
Could you elaborate?

**Comment by matthiasbeyer** [comment]
@TheNeikos ping.

**Comment by TheNeikos** [comment]
Nevermind, I misread I think

**Comment by matthiasbeyer** [comment]
@TheNeikos so we can merge?

**Comment by TheNeikos** [comment]
I think so, perhaps a test :3?

**Comment by matthiasbeyer** [comment]
@TheNeikos I'm not sure about testing here... FS tests are a bit of a pain on travis, you remember?

**Comment by neithernut** [comment]
So... merge?

**Comment by TheNeikos** [comment]
There is one thing I would like to discuss beforehand, that is when it is locked, then I think it should return the 'old' copy.

**Comment by neithernut** [comment]
Interesting idea. It may not be possible in all cases (e.g. if the file is locked by another process) and it would require us to cache the "old" version of the entry (which is doable and may even bring some other benefits with it).

**Comment by TheNeikos** [comment]
I would just try to read the file and if that fails, fail as well.

**Comment by neithernut** [comment]
Nah, reading a locked entry may give you inconsistent data. You don't want that. At least not silently.

**Comment by neithernut** [comment]
Mh... after fiddeling around a little, I did not find any obvious solution which would not require either some redesign of `StoreEntry` and existing methods or impose some ugliness. I'd opt for postponing the extension @TheNeikos proposed. Maybe he could, instead, open an issue where we discuss whether we want this at all and what behaviour/impacts would be acceptable.

**Comment by TheNeikos** [comment]
:+1:

**Comment by neithernut** [comment]
@matthiasbeyer: the current state may still be merged as-is.

**Comment by matthiasbeyer** [comment]
Still would like to see some tests :smile:

**Comment by neithernut** [comment]
Well, that would require me coming up with a test-setup (remember: this function _does_ read from a file, in the end). For this reason, tests of other store methods are also still missing (at least I didn't find any). So... would you _really_ like me to implement testing of essentially store functionality in general in this PR?

**Comment by matthiasbeyer** [comment]
Ah, right... we dicided to not having tests in this case as FS-IO tests suck a bit on travis. Sorry for the inconveniance!

**Pull request merged**
