### PR TITLE
Imag diagnostics/init

### LINKED ISSUE #306: [module]: imag-stat
A simple module which generates some diagnostics about the store.

Could also be named `imag-diagnostics` or `imag-diags`.

Some possible stats:
- [ ] Number of entries
- [ ] Number of entries per collection/module (percentage?)
- [ ] Tags and numbers of entries tagged with each tag
- [ ] Internal links
  - [ ] overall
  - [ ] dead
- [ ] External links
- Average text size of entries
- Average text size of entries with content
- Largest entry
- Maybe even printing graphs

etc etc.

---

We should probably use the [tui](https://github.com/fdehau/tui-rs) crate for this. But I wonder how much it can be used to integrate it into a `Cursive` backed TUI.

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Closes #306

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I want to add some more diagnostics:

- [ ] Average link count per entry
- [ ] Number of internal links
- [ ] Number of external links
  - [ ] Number of dead external links
- [ ] Largest entry
- [ ] Number of entries per collection 

@TheNeikos @mario-kr @asuivelentine More diagnostics suggestions?

**Comment by asuivelentine** [comment]
How about the store version? Something like
234 entries were made wirh version 1
432 made with version 2
...

**Comment by matthiasbeyer** [comment]
Already [done](https://github.com/matthiasbeyer/imag/pull/1136/files#diff-7b34421f313c7d238684431950d050b4R160)

**Comment by matthiasbeyer** [comment]
I guess the current state is a nice one for a initial version of this little helper...

**Pull request merged**
