### PR TITLE
Use cargo feature to specify both version and path

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Thanks to reddit user /u/TimNN for suggesting this.

---

I think whether setting it to "0.4.0" would actually make sense or not. @TheNeikos or @mario-kr -
 suggestions?

### CODE REVIEW

**Comment by mario-kr** [comment]
Definitely a nice change, I guess my prediction was somewhat right ;)

IMHO: I would not make a follow-up release for this change alone. (at least not "0.4.0").

**Comment by matthiasbeyer** [comment]
No, no follow up release. Have a look at the diff. Using the 0.3.0 version string (aka the already released stuff) or the next release?

**Comment by mario-kr** [comment]
If I understand the comment on reddit correctly, there's no need to bump the version to 0.4.0 unless you are about to publish.

**Comment by matthiasbeyer** [comment]
Turns out we actually have to set "0.4.0" so cargo recognizes the internal dependencies.

**Pull request merged**
