### PR TITLE
Libimagstore/git layer

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #108 

@TheNeikos How can I now implement CRUD-git actions? I mean... I'm rather sure git actions should not go to the `impl Store{}` but to some internal sub types, am I right?

Also, as @neithernut suggested, we may not want to make the git operations default (though I'd vote for enabling git by default). For now I will implement this without an on/off switch.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
And of course travis has not all dependencies installed.

**Comment by matthiasbeyer** [comment]
From discussion with @TheNeikos:

We want to be able to switch git on and off via the configuration file (not via the commandline, though).

If the `Store`-Object gets created and afterwards notices that there are uncommited changes we do the following:

* The `Store::new()` function fails with an error
* The user shall update the store with an utility we provide
  * This utility uses a function of the `Store`-object to commit all entry changes
  * This utility provides several switches to 
    * commit the entry-updates on an extra branch
    * (optional but nice-to-have) use a custom commit message

**Comment by neithernut** [comment]
Mh... I don't think that pulling in git as a dependency all the time is a good idea. Can we make this feature (and the dependencies) optional?

**Comment by matthiasbeyer** [comment]
No, I would make it an explicit dependency, actually. One of the basic ideas of the store is to keep historical data. 

Note that we do not pull git as a dependency, but `libgit2`, which should work without git installed, afaik.

**Comment by TheNeikos** [comment]
You would still need it! Which does not come with Rust.

**Comment by matthiasbeyer** [comment]
@TheNeikos are you sure about this? AFAIK implements `libgit2` the git functionality and does not use core-git: https://libgit2.github.com/

This is because `git` itself is GPLv2 and `libgit2` is GPLv2 with linking exception!

**Comment by TheNeikos** [comment]
I did mean `libgit2`, for example it is installed on my Laptop, but it is an extra package.

**Comment by matthiasbeyer** [comment]
Ah, yes. Sure. Anyways, I would make it a hard dependency, the store should be version controlled!

**Comment by matthiasbeyer** [comment]
Discussion appreciated here, as this would be _deeply_ integrated in the store. If we can come up with a "hook"-layer over the store (which we may need anyways, for other things), I would keep this out of the libstore core!
@neithernut , @TheNeikos

**Comment by matthiasbeyer** [comment]
As we are currently discussing (or rather *as I am currently waiting for review on*) a Hook-system in #200 , I will put this on-hold now.

**Comment by matthiasbeyer** [comment]
I guess the hook system will be merged, so I will close this now.

**Pull request closed without merging**
