### PR TITLE
Add store utils

### PR DESCRIPTION
**Pull request by TheNeikos**
Do not merge yet!!

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@TheNeikos is there any progress here? AFAIK, we don't need this PR to get other things finished, right?

**Comment by TheNeikos** [comment]
Nope, this is not blocking

**Comment by TheNeikos** [comment]
@matthiasbeyer @neithernut Review pls

**Comment by matthiasbeyer** [comment]
Let me say: This is awesome!

**Comment by TheNeikos** [comment]
:D Thanks! :dancer: 

Okay, I've put it into a module on it's own to not polute it with unneeded imports or otherwise.

**Comment by matthiasbeyer** [comment]
@homu r+

**Comment by matthiasbeyer** [comment]
@homu retry

**Comment by matthiasbeyer** [comment]
homu is broken and this was already merged. Will close for now.

**Pull request closed without merging**
