### PR TITLE
Try to fix travis AGAIN

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I'm getting really annoyed by this travis bullshit!

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@malept can you tell what's going on here? Somehow the update to rustc 1.17 and cargo 0.18 broke the mechanism that found the `libruby.so.2.3.3` before... that's fixed now but now I'm running into thie error shown here: https://travis-ci.org/matthiasbeyer/imag/jobs/226836806

I squashed the history now. Maybe https://github.com/matthiasbeyer/imag/pull/925/commits/6252f9b2dfb7ffc4eb38b9f53af0813f50032ed7 should be reverted to get this fixed... I don't know (will push a revert shortly, then we'll see whether this fixes the build)

**Comment by malept** [comment]
I can take a look at your PRs this weekend.

**Comment by matthiasbeyer** [comment]
You are awesome, thank you a lot!

**Comment by matthiasbeyer** [comment]
@malept careful *ping* :heart:

**Comment by matthiasbeyer** [comment]
We're moving away from the idea having a Ruby API, but instead we're exporting things via stdio, so we can have ruby scripts in the call-chain.

This gets closed therefor.

**Pull request closed without merging**
