### PR TITLE
Debug logging to trace logging

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Moves some `debug!()` log output to `trace!()` level.

My policy on this is: If you print variables in the log output, it might be a good idea to `trace!()` instead of `debug!()`. `debug!()` should be done for _what is done_ and `trace!()` for _what data is used_.

Feel free to argue on the single diffs.

### CODE REVIEW

**Comment by TheNeikos** [comment]
I disagree on the semantics. Trace is meant to *trace* what is going on, i.e. single steps in an algorithm.

**Comment by matthiasbeyer** [comment]
@TheNeikos this is what these logging calls do... they print values between computations in algorithms.

**Comment by TheNeikos** [comment]
No, trace is below debug, or at least should be. Debug is for general system information. Trace is for **every** *single* step!

**Comment by matthiasbeyer** [comment]
So you think I should close this unmerged, right?

**Pull request closed without merging**
