### PR TITLE
Redo ruby build setup

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Redo the reverted merge from #894 

Lets see whether this fails or not.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
CC @malept

**Comment by matthiasbeyer** [comment]
@malept it seems to fail because with the following configuration:

```
rustc 1.15.0-beta.3
cargo 0.17.0
```

The `liblibimagruby.so` file gets put into `/target/debug/deps/liblibimagruby.so`, and `thermite` does not find it there.

I guess I have no way to configure this on my side, so I guess `thermite` needs another update for this.

I suggest that `thermite` gets a flag for searching a directory recursively...

**Comment by malept** [comment]
I can't seem to reproduce this locally. I'm using rustup to change versions:

```
$ cargo --version; rustc --version
cargo-0.17.0-nightly (dfc0f95 2017-02-01)
rustc 1.16.0-beta.1 (5276ba72e 2017-01-31)
```

When I run `CARGO_TARGET=debug bundle exec rake thermite:tarball`, I get a very large (52MB) shared library at `lib/liblibimagruby.so`.

**Comment by matthiasbeyer** [comment]
I guess I'll go over to the cargo guys and ask them...

**Comment by malept** [comment]
@matthiasbeyer Here's what I've been doing (all in the `libimagruby` directory, because that's where the `Gemfile` is):

```shell
$ rustup override set stable
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
# etc.
$ cargo --version; rustc --version
cargo 0.16.0-nightly (6e0c18c 2017-01-27)
rustc 1.15.0 (10893a9a3 2017-01-19)
$ bundle exec rake thermite:clean
checking for cargo... yes
~/.cargo/bin/cargo clean --manifest-path libimagruby/Cargo.toml
$ ls ../target
ls: cannot access ../target: No such file or directory
$ ls lib
imag  imag.rb
$ CARGO_TARGET=debug bundle exec rake thermite:tarball
checking for cargo... yes
~/.cargo/bin/cargo rustc --manifest-path libimagruby/Cargo.toml
Compiling [...]
$ ls lib
imag  imag.rb  liblibimagruby.so
$ ls ../target
debug
$ rustup override set beta
info: using existing install for 'beta-x86_64-unknown-linux-gnu'
# etc.
$ cargo --version; rustc --version
cargo-0.17.0-nightly (dfc0f95 2017-02-01)
rustc 1.16.0-beta.1 (5276ba72e 2017-01-31)
$ bundle exec rake thermite:clean
checking for cargo... yes
~/.cargo/bin/cargo clean --manifest-path libimagruby/Cargo.toml
$ ls ../target
ls: cannot access ../target: No such file or directory
$ ls lib
imag  imag.rb
$ CARGO_TARGET=debug bundle exec rake thermite:tarball
checking for cargo... yes
~/.cargo/bin/cargo rustc --manifest-path libimagruby/Cargo.toml
Compiling [...]
$ ls lib
imag  imag.rb  liblibimagruby.so
$ ls ../target
debug
```

**Comment by matthiasbeyer** [comment]
@malept Hm...  strange things are happening here...

---

Minified travis output:

```
$ rustc --version
rustc 1.15.0 (10893a9a3 2017-01-19)
$ cargo --version
cargo 0.16.0-nightly (6e0c18c 2017-01-27)
$ rvm install "$IMAG_RUBY_VERSION"
  rvm use "$IMAG_RUBY_VERSION"
  ruby --version
  pushd libimagruby
  bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/libimagruby/vendor/bundle
  popd
Resolving dependencies...
Using rake 10.5.0
Using bundler 1.14.3
Using imag 0.1.0 from source at `.`
Using minitar 0.5.4
Using tomlrb 1.2.3
Using thermite 0.11.1
Bundle complete! 4 Gemfile dependencies, 6 gems now installed.
Bundled gems are installed into ./vendor/bundle.
~/build/matthiasbeyer/imag
	[CARGO  ]:	imag-link
	[CARGO  ]:	imag-notes
	[CARGO  ]:	imag-ref
	[CARGO  ]:	imag-store
	[CARGO  ]:	imag-tag
	[CARGO  ]:	imag-view
	[CARGO  ]:	libimagentryedit
	[CARGO  ]:	libimagentryfilter
	[CARGO  ]:	libimagentrylink
	[CARGO  ]:	libimagentrylist
	[CARGO  ]:	libimagentrymarkdown
	[CARGO  ]:	libimagentrytag
	[CARGO  ]:	libimagentryview
	[CARGO  ]:	libimagerror
	[CARGO  ]:	libimaginteraction
	[CARGO  ]:	libimagnotes
	[CARGO  ]:	libimagref
	[CARGO  ]:	libimagrt
	[CARGO  ]:	libimagruby
	[CARGO  ]:	libimagstore
	[CARGO  ]:	libimagstorestdhook
	[CARGO  ]:	libimagtimeui
	[CARGO  ]:	libimagutil
	[IMAG   ][BUILD  ]
	[ALL    ]
	[BINTEST]:	imag-link-test
	[BASH   ]:	link-test.sh
	[BINTEST]:	imag-notes-test
	[BINTEST]:	imag-ref-test
	[BINTEST]:	imag-store-test
	[BASH   ]:	001-create_test.sh
	[BASH   ]:	002-retrieve_test.sh
	[BASH   ]:	003-delete_test.sh
	[BINTEST]:	imag-tag-test
	[BINTEST]:	imag-view-test
	[TEST   ]:	libimagentryedit-test
	[TEST   ]:	libimagentryfilter-test
	[TEST   ]:	libimagentrylink-test
	[TEST   ]:	libimagentrylist-test
	[TEST   ]:	libimagentrymarkdown-test
	[TEST   ]:	libimagentrytag-test
	[TEST   ]:	libimagentryview-test
	[TEST   ]:	libimagerror-test
	[TEST   ]:	libimaginteraction-test
	[TEST   ]:	libimagnotes-test
	[TEST   ]:	libimagref-test
	[TEST   ]:	libimagrt-test
	[TEST   ]:	libimagruby-test
	[TEST   ]:	libimagstore-test
	[TEST   ]:	libimagstorestdhook-test
	[TEST   ]:	libimagtimeui-test
	[TEST   ]:	libimagutil-test
make[1]: Entering directory `/home/travis/build/matthiasbeyer/imag/libimagruby'
[RAKE  ][thermite]
checking for cargo... yes
/home/travis/rust/bin/cargo rustc --manifest-path libimagruby/Cargo.toml
    Finished debug [unoptimized + debuginfo] target(s) in 0.1 secs
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ../target/debug/liblibimagruby.so
/home/travis/build/matthiasbeyer/imag/libimagruby/vendor/bundle/ruby/2.3.0/gems/thermite-0.11.1/lib/thermite/tasks.rb:126:in `block in define_build_task'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `load'
/home/travis/.rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `<main>'
/home/travis/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => thermite:tarball => thermite:build
(See full trace by running task with --trace)
make[1]: *** [bundle-rake-thermite-test] Error 1
make[1]: Leaving directory `/home/travis/build/matthiasbeyer/imag/libimagruby'
make: *** [lib-imag-ruby-test] Error 2


The command "make all test
" exited with 2.
```

**Comment by malept** [comment]
Why does yours say "Finished debug [unoptimized + debuginfo] target(s)", while mine says "Finished dev [unoptimized + debuginfo] target(s)"?

Perhaps there's something to do with the fact that you're pre-building everything? My command takes about 2 minutes whereas yours takes 0.1 seconds.

**Comment by matthiasbeyer** [comment]
Reproduced with

```
cargo 0.16.0
rustc 1.15.0
```

and building the `libimagruby` directly:

```
    Finished debug [unoptimized + debuginfo] target(s) in 67.50 secs
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ../target/debug/liblibimagruby.so
/home/m/kernel/imag/libimagruby/vendor/bundle/ruby/2.3.0/gems/thermite-0.11.1/lib/thermite/tasks.rb:126:in `block in define_build_task'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/bin/bundle:18:in `load'
/nix/store/6jjj4f3a7xh71c4yz5rvr3cpl0llhxji-bundler-1.14.3/bin/bundle:18:in `<main>'
Tasks: TOP => thermite:tarball => thermite:build
(See full trace by running task with --trace)
make: *** [Makefile:14: bundle-rake-thermite-test] Error 1
```

**Comment by matthiasbeyer** [comment]
Waiting for https://github.com/matthiasbeyer/imag/pull/915

**Pull request merged**
