### PR TITLE
Libimagstorestdhook/init

### PR DESCRIPTION
**Pull request by matthiasbeyer**
std hook library.

Will introduce only a debug hook in this init PR, later VCS and encryption can be added in seperate PRs.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Pending:

* Hooks are not configured in the configuration which gets generated with `--debug`
  * Aspect configuration
  * Parallelization

After this is done, we can test the hook system. I hope it works as expected! :unamused:

**Comment by matthiasbeyer** [comment]
Cherry picks were submitted in #272, #273, #274, #275 and #276 and will vanish as this gets rebased after the others were merged.

I tested this with `imag-store` and the debug hook runs as expected.

**HOW AWESOME IS THIS??? CAN YOU BELIEVE IT???**

@TheNeikos @neithernut

**Comment by matthiasbeyer** [comment]
I'd like to merge #277 before this as well.

**Comment by neithernut** [comment]
Nice.
However, I'd like to postpone the review until the cherry-picked commits vanished through a rebase.

**Comment by matthiasbeyer** [comment]
@neithernut Yep.

**Comment by matthiasbeyer** [comment]
Waiting on even more extracted bug fixes. Waiting on these now:

#272 
#273 
#274
#275 
#276 
#287 
#288 
#289 
#290

**Pull request merged**
