### PR TITLE
Fix Store::get()

### LINKED ISSUE #445: Store::get() only gets from store internal cache, not FS
The store function `get` only asks the store cache for the entries, not the filesystem.

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Closes #445 

@TheNeikos review? I know the code is ugly, but this small piece took ~2 hrs to craft, so I just committed it and awaiting review now.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Wah, this implicitely creates entries in the store.

Still working on it... :cry:

**Comment by matthiasbeyer** [comment]
@TheNeikos The problem that store entries are getting created are _way_ deep down in `LazyFile`.

I'm not sure we can change this, can we? @TheNeikos you are expert on this level... would be nice to hear from you!

**Comment by matthiasbeyer** [comment]
Sometimes the simple solutions are the best.

**Comment by TheNeikos** [comment]
Love your solution haha

**Comment by matthiasbeyer** [comment]
Yeah ... I mean it is a hack, but a valid one, isn't it?

**Pull request merged**
