### PR TITLE
Libimagstore/add storeid iter

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Proposal for #138

### CODE REVIEW

**Comment by neithernut** [comment]
You introduced a `StoreIdIterator` but `retrieve_for_module()` returns a `Vec<Result<StoreId>>`?
And why `Vec<Result<StoreId>>`? Why not `Vec<StoreId>`?

**Comment by matthiasbeyer** [comment]
Because this is not ready at all :sunglasses:

**Comment by matthiasbeyer** [comment]
And if you had commented on the diff, your comment would've been vanished by now.

**Comment by matthiasbeyer** [comment]
@TheNeikos What do you think?

**Comment by TheNeikos** [comment]
I don't see anything wrong :?

**Comment by neithernut** [comment]
Looks fine.

**Pull request merged**
