### PR TITLE
Libimagstore/warn-to-err

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Removes a bunch of warnings and then turns on the warning-as-error flags for some lints.

@TheNeikos review pls.

### CODE REVIEW

**Comment by TheNeikos** [comment]
Doesn't build :frowning:

**Comment by matthiasbeyer** [comment]
Thafug? I built it locally before pushing... but I didn't ran the tests... I'll investigate later this day!

**Comment by matthiasbeyer** [comment]
Dafuq it actually builds for me... I do not understand this!

**Comment by matthiasbeyer** [comment]
Okay, I guess I was too tired. It was the tests. I fixed it.

@TheNeikos please review.

**Pull request merged**
