### PR TITLE
Libimagtag/init

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets the specification from #173

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@TheNeikos may I recieve your suggestions on the CI error?

**Comment by matthiasbeyer** [comment]
Note: We must ensure that a tag only occurs one.

**Comment by TheNeikos** [comment]
How about letting toml do that for us? Make it a table with the key being the tag and the value being the add_date or something.

**Comment by matthiasbeyer** [comment]
So you would attach even metadata to a tag? Hm... I must say I don't like that idea. Just for the sake of simplicity of our codebase introducing some overhead... nah, sorry, I don't like that.

**Comment by neithernut** [comment]
It would also go against the widespread concept of a "tag", IMO.

**Comment by matthiasbeyer** [comment]
@TheNeikos can you investigate why this PR fails?

**Comment by matthiasbeyer** [comment]
This is on hold until #149 is merged, as this PR would greatly simplify this PR.

**Comment by neithernut** [comment]
I don't see anything fishy.

**Comment by matthiasbeyer** [comment]
@neithernut is this "ack for merging"?

**Comment by neithernut** [comment]
It's an "I think it is ok for merging. I didn't invest much time in inspecting it, though."

**Pull request merged**
