### PR TITLE
Libimagstorestdhook/flock

### LINKED ISSUE #175: Store does not `flock()` yet
AFAICS, the store does not `flock()` an entry, yet. We should implement this.

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Closes #175

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Ready for review here.

**Comment by TheNeikos** [comment]
I like the interface you made :+1:

**Comment by matthiasbeyer** [comment]
Which interface do you mean? The hook API?

So do you think I can merge this?

**Comment by TheNeikos** [comment]
Yes, and yes.

**Pull request merged**
