### PR TITLE
Libimagutil/add kv splitter

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This will be useful for the commandline interface lateron.

Review appreciated. Also have a look at the tests, how wonderful I made the interface to this functionality ( :smile: )!

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Funny that aa672b5 succeeds on the beta compiler...

**Comment by TheNeikos** [comment]
Looks okay to me

**Comment by neithernut** [comment]
Isn't this supported by the framework we use for command line parsing?

**Comment by matthiasbeyer** [comment]
@neithernut Nope. You can do `--foo bar` but you cannot do `--foo bar=baz` and get "k: bar, v: baz" from it.

**Comment by matthiasbeyer** [comment]
Fixup done.
@neithernut can I merge?

**Comment by neithernut** [comment]
Still wondering why `clap::App` doesn't support this already. I guess it can't be helped. ACK for merge.

**Comment by matthiasbeyer** [comment]
@homu r+

**Comment by matthiasbeyer** [comment]
@homu retry

**Comment by TheNeikos** [comment]
Uhm, what happened here? Only 1 of three tests passed? Stable could not be installed???

**Comment by matthiasbeyer** [comment]
@TheNeikos What do you see? I see https://travis-ci.org/matthiasbeyer/imag/builds/103658346, which is fine... Or do you mean the one before my *retry*?

**Comment by TheNeikos** [comment]
https://i.imgur.com/DlCseel.png

This one I mean

**Comment by matthiasbeyer** [comment]
Ummm...

**Comment by matthiasbeyer** [comment]
I just ran 

```bash
for n in libimagstore libimagutil/ libimagrt/ libimagmodule/; do cd $n; cargo build && cargo test; cd -; done
```

on master locally and it builds. So yes,... worked. Though homu clearly fucked up above.

**Comment by matthiasbeyer** [comment]
Aahhh, I can see it now: @TheNeikos Homu merged because the merge-commit succeeded the tests, though the PR itself didn't. This is valid IMHO, as several developers could implement things in parallel, even if there are dependencies between the things they are implementing. If the order of merges is correct, the PR might fail but the merge-commit will build.

**Pull request merged**
