### PR TITLE
Add travis-to-gh-pages after_success

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Add github-pages building from travis.

I hope this works, as our setup (with multiple crates and so on) is a bit different from the normal setup.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Seems like doc generating finally works, though pushing does not work. @TheNeikos do you know why?

**Comment by TheNeikos** [comment]
Yeah, only builds on master will actually push anything

**Comment by matthiasbeyer** [comment]
@TheNeikos See the build log of the latest build. It tried to push, though it failed because the access was denied...

**Comment by TheNeikos** [comment]
@matthiasbeyer Ok, is `14cd11b521801109fbfc00842eba46839da6ddec` your access token btw?

**Comment by matthiasbeyer** [comment]
Where did you get this hash from? And ... I'm not sure, why?

**Comment by matthiasbeyer** [comment]
Ah, I can see where you got it from. Why the fuck does travis show you this?

**Comment by TheNeikos** [comment]
If it is, invalidate it ;)

**Comment by matthiasbeyer** [comment]
@TheNeikos I already did this, right after I read your comment.

**Comment by matthiasbeyer** [comment]
Closing because this is too old and stalled.

**Pull request closed without merging**
