### PR TITLE
doc: Add basic file structure

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Adds some basic file structure for the document.

### CODE REVIEW

**Comment by neithernut** [comment]
`doc/src/0500-lib-module` is missing the `.md` suffix

**Comment by neithernut** [comment]
Also, I'm not quite sure the list of commands and the list of modules should be that long just now or whether it should be extended as more and more gets implemented.

**Comment by matthiasbeyer** [comment]
@neithernut I'll remove some by commenting them out.

**Comment by neithernut** [comment]
Still thinking... wouldn't it be better if each module had it's own file, also containing the module-specific command descriptions?

**Comment by matthiasbeyer** [comment]
@neithernut looks good now, doesn't it? As soon as there are issues for the implementation opened (or PRs), I'd merge this and start documenting things.

**Comment by neithernut** [comment]
Yep, this is better.

**Comment by matthiasbeyer** [comment]
@homu r+

**Pull request merged**
