### PR TITLE
libimagstore/store: tests allowed erroring hooks

### PR DESCRIPTION
**Pull request by matthiasbeyer**
PR on #698

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@TheNeikos Can you have a look please? The CI fails with a `PoisonError` - but why? I cannot reproduce localy!

**Comment by matthiasbeyer** [comment]
For the sake of documentation: The first execution of the CI caused 16 tests in the erroring job. The second one caused 26 to fail. Lets see what the third iteration gives us.

**Comment by matthiasbeyer** [comment]
Okay, this scares the shit out of me. The third CI run succeeded.

@TheNeikos What do you think should we do? Run the CI another 100 times? This scares me because it seems to be not that reproducible.

**Comment by TheNeikos** [comment]
Well, if it just happens randomly and only on CI then we can't do much. It's pretty weird but I guess there is not much we can do?

**Comment by matthiasbeyer** [comment]
Okay. Lets see what the merge commit build of this tells us...

**Pull request merged**
