### PR TITLE
Libimagstore/header utils

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Tracking branch for header-parser code utilities in `EntryHeader` type.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Blocked by #122 afaict.

**Comment by TheNeikos** [comment]
#122 has been merged

**Comment by matthiasbeyer** [comment]
@TheNeikos You mean I can merge?

**Comment by neithernut** [comment]
I'm wondering whether the internal error module could be merged with the general libstore error module in a sensible way.

**Comment by matthiasbeyer** [comment]
Nah, I don't like the idea. The error module I'm introducing is header related only (it is actually only header-parser related only), so it is a completely other domain, IMHO.

**Comment by neithernut** [comment]
Wouldn't `MissingMainSection` and `MissingVersionInfo` also make sense in another context? E.g. when preparing/creating an entry?

**Comment by matthiasbeyer** [comment]
@neithernut indeed. Though I'm not sure here how to proceed. We want `::new()` to return a type, not an `Option<type>`, so changing the `::new()` function to do such a check won't be good. I'm not sure how to do verification on creation...

**Comment by neithernut** [comment]
@matthiasbeyer of what `::new()` are you talking about, exactly?

**Comment by matthiasbeyer** [comment]
When creating an `Entry`, we want `Entry::new()` return `Entry`, not `Result<Entry>` ...

**Comment by neithernut** [comment]
Ah, now I get what you problem is. Mh... I guess you don't have a choice here.
Another thing which just popped into my mind: should an `Entry` be created by the user (vs. created and returned by the store)? Think about a user creating an entry which already exists in the store.

**Comment by matthiasbeyer** [comment]
Let us ask @TheNeikos

**Comment by TheNeikos** [comment]
I am not sure about what?

**Comment by matthiasbeyer** [comment]
> shoukd an Entry be created by the user vs. Created and returned by the store?

**Comment by TheNeikos** [comment]
Returned by the store

**Comment by matthiasbeyer** [comment]
Okay, so I will not implement `::new()` on `Entry`. :smile:

**Comment by TheNeikos** [comment]
See #131

**Comment by matthiasbeyer** [comment]
#131 is about `EntryHeader::new()`, not `Entry::new()`, ... or what do you mean?

**Comment by TheNeikos** [comment]
Same reasoning, don't let the user create one explicitely.

**Comment by matthiasbeyer** [comment]
I have not implemented any `::new()` in this PR, except one for an error type... So I'm not sure what you want from me...

**Comment by TheNeikos** [comment]
Nothing :D But I just like to crossref things to keep discussions together

**Comment by matthiasbeyer** [comment]
And what is the conclusion on this PR? Ack?

**Comment by neithernut** [comment]
If the error types I mentioned are not being put into `libstore`'s general error module.

**Comment by matthiasbeyer** [comment]
Nope, I wouldn't do that, as the domain of the errors is different. The error (and its `..Kind` will be exported through `StoreError.cause` anyways, so that wouldn't be an issue, but putting the error code into the main error module does not make sense to me in a semantical way.

**Comment by matthiasbeyer** [comment]
@neithernut Do you ACK? Homu is dead, so I have to merge manually. Actually, I have to rebase first, but I think I won't change any content anymore.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
