### PR TITLE
Fixup unused warnings.

### PR DESCRIPTION
**Pull request by jsirois**

### CODE REVIEW

**Comment by jsirois** [comment]
Found these working #532 and thought I should clean them up.

**Comment by matthiasbeyer** [comment]
Wow. Awesome! I will have a closer look later or tomorrow. Thanks a lot for your contribution(s)! :-)

**Comment by matthiasbeyer** [comment]
Would you mind to split up the patch into two commits, one where you remove the import and one where you remove the other piece of code?

Besides that, this looks fine to me and I'd merge it after the splitup.

**Comment by jsirois** [comment]
Will do.

**Comment by matthiasbeyer** [comment]
Wow, thanks. Would've been enough to just split into two commits and push to this PR, but well... thanks! I will merge the other ones after review. :+1:

**Pull request closed without merging**
