### PR TITLE
Reorganize code in subdirs

### PR DESCRIPTION
**Pull request by matthiasbeyer**
A porposal to move things into subdirs, to lessen the amount of things in the root repository.

@TheNeikos I'd love to have comments from you on this one!

### CODE REVIEW

**Comment by TheNeikos** [comment]
I like the idea :+1:

**Comment by matthiasbeyer** [comment]
Okay. I will do this post-0.3.0 because I really should get 0.3.0 done.

**Comment by matthiasbeyer** [comment]
Blocked by https://github.com/matthiasbeyer/imag/pull/1006

**Comment by matthiasbeyer** [comment]
I cannot get this to work. @mario-kr and @TheNeikos do you have any ideas? For me, cargo simply does not find the package dependencies for each build. I don't know why and my experiments didn't succeed.

Setting the `package.workspace` key for each crate does not help (the cargo docs state that, if the key is not present, the first Cargo.toml upwards the filesystem is used... which is the `/Cargo.toml` of our project).

Using a `/lib/core/libimagstore` dependency path or a `lib/core/libimagstore` didn't work, so I kept the `../../../lib/core/libimagstore` one.

Ideas?

**Comment by mario-kr** [comment]
oh btw: pretty much all links are broken (README.md -> ../doc/something)

**Comment by matthiasbeyer** [comment]
> oh btw: pretty much all links are broken (README.md -> ../doc/something)

Yep, I know that, just did not yet fix them.

**Comment by matthiasbeyer** [comment]
@mario-kr I had to rebase and squashed your patches away. Is this okay with you?

**Comment by mario-kr** [comment]
yes it is

**Comment by mario-kr** [comment]
```
> rg --hidden /libimagentrytimetrack
.imag-documentation/Cargo.toml
31:libimagentrytimetrack  = { version = "0.4.0", path = "../lib/entry/libimagentrytimetrack" }
```

**Comment by matthiasbeyer** [comment]
Ah, thanks. The fix is included in the commit already, hopefully we can merge this soonish (without another rebase, hopefully)

**Pull request merged**
