### PR TITLE
[RFC] Add content type

### PR DESCRIPTION
**Pull request by neithernut**
This PR makes `EntryContent` a container holding the type of the (textual) content.
Related to one aspect discussed in #120.

### CODE REVIEW

**Comment by TheNeikos** [comment]
I do not think that there should be a content type as so much as a hint to the library that created it, thus leaving it up to the library to make such an entry.

So I do not think that that this belongs in the store itself.

**Comment by neithernut** [comment]
I'm not sure I get your point. You mean the `EntryContentType` is in the wrong place? Or the content-type should be stored in a completely different way?

**Comment by TheNeikos** [comment]
I think that the content type should not be stored by the store at all. It itself does not need any notion of what the file is it points to, so why encode it into the store library?

**Comment by neithernut** [comment]
You may have missed something: both @matthiasbeyer and I pointed out that, for textual content stored in the item file itself, you need a way to tell how the text is formatted or whether it is formatted at all (hence `Plain`).
Viewers may rely on this because, in contrast to external files, there is no single hint of the text format, except looking at it and taking an educated guess.

**Comment by matthiasbeyer** [comment]
@neithernut Wait for the doc-PR of @TheNeikos . We discussed and things got cleared up, just wait until the PR is there and then we can argue about details, but things are defined already (though not carved into stone).

**Comment by TheNeikos** [comment]
Since store items should only be loaded through their respective modules (as we've discussed in #58) shouldn't that mean that whoever loads the file leave it to the respective library? 
I would wait until #58 iss resolved and then resume here.

**Comment by neithernut** [comment]
Item files are loaded via the store only. At least that's what I thought. Waiting for the PR now...

**Comment by matthiasbeyer** [comment]
I guess we can close this unmerged as this is done in a completely different way. @TheNeikos ?

**Comment by TheNeikos** [comment]
I think so yes, hence my initial comments

**Pull request closed without merging**
