### PR TITLE
Travis small enhancements

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Some small enhancements to the current travis setup.

Should be ready.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Wow... am I wrong or is this significantly faster than before? I mean 50 mins vs. ~30 mins?

@TheNeikos can you have a look? Am I overlooking something? Maybe also @neithernut ?

**Comment by TheNeikos** [comment]
LGTM

**Comment by matthiasbeyer** [comment]
@TheNeikos thanks, I guess I will wait until someone else has had a look ... just to be sure.

**Comment by matthiasbeyer** [comment]
@TheNeikos you can also have a look at the latest commit,... I guess this is even better, right?

**Comment by TheNeikos** [comment]
Yes indeed

**Comment by neithernut** [comment]
Looks good.

**Pull request merged**
