### PR TITLE
travis: Add code-coverage

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Taken from

    https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650

Thank you nice Rustaceans!

---

Adds code-coverage generating. Is not uploaded to $somewhere yet.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
It seems to work now, doesn't it?

**Comment by TheNeikos** [comment]
I am not sure: https://travis-ci.org/matthiasbeyer/imag/jobs/111497514#L2225

**Comment by matthiasbeyer** [comment]
brah. I don't know why this is happening. Anyways, this is low prio.

**Comment by matthiasbeyer** [comment]
Closing because this is too old and stalled.

**Pull request closed without merging**
