### PR TITLE
travis: cache all target/ directories and $HOME/.cargo

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@killercup did I get this right? Could you have a look?

**Comment by killercup** [comment]
@matthiasbeyer, it's hard to say whether this works. But you can test it—just add another commit that changes one crate and see if cargo can use the cached results.

If you want to get workspaces working, you should also add `$TRAVIS_BUILD_DIR/target` as the workspace will probably use the parent directory.

**Comment by matthiasbeyer** [comment]
I would say that it won't hurt to include that and as it is only a small patch we can revert it easily if something breaks. I will merge this if CI succeeds and we'll see...

**Comment by matthiasbeyer** [comment]
I completely forgot about this one.

**Comment by matthiasbeyer** [comment]
@mario-kr This should speed up the travis builds even more :smile:

**Comment by mario-kr** [comment]
Hmm, no real benefits. `$HOME/.cargo` might be more important to cache, as all the 3rd party crates are in there. Though that would require a `cargo update` some times...

**Comment by matthiasbeyer** [comment]
> Hmm, no real benefits. $HOME/.cargo might be more important to cache, as all the 3rd party crates are in there.

This is done by the `cargo: true` part.

**Pull request closed without merging**
