### PR TITLE
Libimagstore/hook configuration

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is a PR on #225 which itself is a PR to #200 .

This is a proposal for hook configuration helpers, it contains commits from #231 , which will vanish after #231 is merged and this is rebased.

@TheNeikos, @neithernut  review please!

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Badum... zzzzz..

It's compiling. I'm ready for review here, @TheNeikos , @neithernut

**Comment by neithernut** [comment]
Looks good so far.

**Comment by matthiasbeyer** [comment]
@neithernut you noted that this is a PR to a PR to a PR to master and reviewed _everything_, or you just reviewed this very PR?

**Comment by neithernut** [comment]
I only reviewed this PR. I prefer to review the PR this one is based on after the merge -- if you do a fast-forward merge.

**Comment by matthiasbeyer** [comment]
Okay, will merge this now.

I won't do a FF merge, though I want to rebase the PR which goes into master as soon as it is ready, the merge commits will vanish then and maybe we can extract some commits for this before merging.

**Pull request merged**
