### PR TITLE
Added .value_name() fields.

### PR DESCRIPTION
**Pull request by uomoinverde**
Job almost completed. My first experience in Rust, trying to learn by doing. Addresses #397.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Hey, awesome you contribute some code!

The commits look really good to me, would you mind removing the issue number from the commit messages? Just `"Add .value_name() call"` or something like this? Would be awesome!

**Comment by uomoinverde** [comment]
Ok, I re-commited (corrected a couple of typos). How should I act in the future? Should I never reference to the issue? I think a contributing guide would help you gathering contributors. :-)

**Comment by uomoinverde** [comment]
Sorry, still new to the mechanism of Git. I've involutarily commited the doc change, I'm trying to undo this but can't find the way.

**Comment by matthiasbeyer** [comment]
Ummm,... you rebased and got some commits which were already merged into master into this PR somehow.


I'd suggest you do the following (if you are on your branch, which is `master`, assuming `origin` is the remote refering to this repository):

```bash
git rebase origin master
```

---

If you do care to completely re-file this PR (as PRs should always start from a "feature-branch"), do the following:

```bash
git checkout origin/master
git checkout -b add-value-name-fields
git cherry-pick d56d8dc d2f9b1d da05e0d c54e14a 877514e
git push <your remote name> add-value-name-fields
```

`cherry-pick` includes a commit-message rewrite as far as I know, so you can fix the commit messages in one step as well.

You can then close this PR and open a new one from the new branch (named "add-value-name-fields").

If everything worked, you can `git checkout master && git reset --hard origin/master` to reset your local master branch to my upstream master branch. If you want to save the "doc" commit before (and maybe file another PR for this improvement :smile:) you can

```bash
git checkout origin/master
git checkout -b add-doc-links
git cherry-pick c758908
```

**before** doing the `master` reset.

---

Either way, I fetched your commits and they are backed up locally on my machine, so if you mess up I can refile your PR with your commits, but I'd suggest you try yourself for the learning experience. You can read more on git in [the git book](https://www.git-scm.com/doc) and on rebasing [in the appropriate chapter](https://www.git-scm.com/book/en/v2/Git-Branching-Rebasing) if you want to.

Feel free to ask questions here.

---

And I wanted to say thank you for getting in touch and filing PRs! Awesome of you!

**Pull request closed without merging**
