### PR TITLE
Ruby tests

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This branch adds tests for the `libimagruby` gem.

WIP.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Maybe @malept could provide review and/or suggestions here as well? :smile: 
I'm not sure whether the way I do the test setup is even sane...

**Comment by matthiasbeyer** [comment]
Should wait on #871

**Comment by malept** [comment]
Personally, I would go with unit tests instead of rspec, because:

* Less to install (minitest is bundled with Ruby)
* They're closer to what the built-in Rust testing framework looks like

But obviously, you should use whatever you're more comfortable with.

Regarding how the tests themselves should be structured, I would write them in the following way, to make sure that the Ruru glue code works as you expect:
* Can I use method X? (as opposed to "does it exist")
* Does method X translate the arguments/return value to/from the Rust function correctly?

_(This assumes that there are sufficient Rust unit tests for the Rust logic.)_

**Comment by matthiasbeyer** [comment]
This is superceeded by #889 - closing therefor.

**Pull request closed without merging**
